In [18]:
from pymongo import MongoClient
import pandas as pd
client = MongoClient()
db = client.test

In [19]:
result = db.restaurants.update_one(
    {"name": "Juni"},
    {
        "$set": {
            "cuisine": "American (New)"
        },
        "$currentDate": {"lastModified": True}
    }
)

In [20]:
result.matched_count

1

In [21]:
result.modified_count

1

In [22]:
result = db.restaurants.update_one(
    {"restaurant_id": "41156888"},
    {"$set": {"address.street": "East 31st Street"}}
)

In [23]:
result.matched_count

1

In [24]:
result.modified_count

0

In [25]:
result = db.restaurants.update_many(
    {"address.zipcode": "10016", "cuisine": "Other"},
    {
        "$set": {"cuisine": "Category To Be Determined"},
        "$currentDate": {"lastModified": True}
    }
)

In [26]:
result.matched_count

0

In [27]:
result.modified_count

0

In [14]:
data = pd.DataFrame(list(db.restaurants.find()))

In [15]:
data

,_id,address,borough,cuisine,grades,lastModified,name,restaurant_id
0,562601afba002f1395be1245,"{u'building': u'1007', u'street': u'Morris Par...",Bronx,Bakery,"[{u'date': 2014-03-03 00:00:00, u'grade': u'A'...",NaN,Morris Park Bake Shop,30075445
1,562601afba002f1395be1246,"{u'building': u'351', u'street': u'West 57 S...",Manhattan,Irish,"[{u'date': 2014-09-06 00:00:00, u'grade': u'A'...",NaN,Dj Reynolds Pub And Restaurant,30191841
2,562601afba002f1395be1247,"{u'building': u'2780', u'street': u'Stillwell ...",Brooklyn,American,"[{u'date': 2014-06-10 00:00:00, u'grade': u'A'...",NaN,Riviera Caterer,40356018
3,562601afba002f1395be1248,"{u'building': u'97-22', u'street': u'63 Road',...",Queens,Jewish/Kosher,"[{u'date': 2014-11-24 00:00:00, u'grade': u'Z'...",NaN,Tov Kosher Kitchen,40356068
4,562601afba002f1395be1249,"{u'building': u'8825', u'street': u'Astoria Bo...",Queens,American,"[{u'date': 2014-11-15 00:00:00, u'grade': u'Z'...",NaN,Brunos On The Boulevard,40356151
5,562601afba002f1395be124a,"{u'building': u'469', u'street': u'Flatbush Av...",Brooklyn,Hamburgers,"[{u'date': 2014-12-30 00:00:00, u'grade': u'A'...",NaN,Wendy'S,30112340
6,562601afba002f1395be124b,"{u'building': u'2206', u'street': u'Victory Bo...",Staten Island,Jewish/Kosher,"[{u'date': 2014-10-06 00:00:00, u'grade': u'A'...",NaN,Kosher Island,40356442
7,562601afba002f1395be124c,"{u'building': u'7114', u'street': u'Avenue U',...",Brooklyn,Delicatessen,"[{u'date': 2014-05-29 00:00:00, u'grade': u'A'...",NaN,Wilken'S Fine Food,40356483
8,562601afba002f1395be124d,"{u'building': u'6409', u'street': u'11 Avenue'...",Brooklyn,American,"[{u'date': 2014-07-18 00:00:00, u'grade': u'A'...",NaN,Regina Caterers,40356649
9,562601afba002f1395be124e,"{u'building': u'1839', u'street': u'Nostrand A...",Brooklyn,"Ice Cream, Gelato, Yogurt, Ices","[{u'date': 2014-07-14 00:00:00, u'grade': u'A'...",NaN,Taste The Tropics Ice Cream,40356731
10,562601afba002f1395be124f,"{u'building': u'1269', u'street': u'Sutter Ave...",Brooklyn,Chinese,"[{u'date': 2014-09-16 00:00:00, u'grade': u'B'...",NaN,May May Kitchen,40358429
11,562601afba002f1395be1250,"{u'building': u'705', u'street': u'Kings Highw...",Brooklyn,Jewish/Kosher,"[{u'date': 2014-11-10 00:00:00, u'grade': u'A'...",NaN,Seuda Foods,40360045
12,562601afba002f1395be1251,"{u'building': u'1', u'street': u'East 66 Str...",Manhattan,American,"[{u'date': 2014-05-07 00:00:00, u'grade': u'A'...",NaN,1 East 66Th Street Kitchen,40359480
13,562601afba002f1395be1253,"{u'building': u'265-15', u'street': u'Hillside...",Queens,"Ice Cream, Gelato, Yogurt, Ices","[{u'date': 2014-10-28 00:00:00, u'grade': u'A'...",NaN,Carvel Ice Cream,40361322
14,562601b2ba002f1395be620f,"{u'building': u'42', u'street': u'Broadway', u...",Queens,Other,[],NaN,Laquana King,50003441
15,562601afba002f1395be1252,"{u'building': u'203', u'street': u'Church Aven...",Brooklyn,"Ice Cream, Gelato, Yogurt, Ices","[{u'date': 2014-02-10 00:00:00, u'grade': u'A'...",NaN,Carvel Ice Cream,40360076
16,562601afba002f1395be1254,"{u'building': u'6909', u'street': u'3 Avenue',...",Brooklyn,Delicatessen,"[{u'date': 2014-08-21 00:00:00, u'grade': u'A'...",NaN,Nordic Delicacies,40361390
17,562601afba002f1395be1255,"{u'building': u'2300', u'street': u'Southern B...",Bronx,American,"[{u'date': 2014-05-28 00:00:00, u'grade': u'A'...",NaN,Wild Asia,40357217
18,562601afba002f1395be1256,"{u'building': u'522', u'street': u'East 74 S...",Manhattan,American,"[{u'date': 2014-09-02 00:00:00, u'grade': u'A'...",NaN,Glorious Food,40361521
19,562601afba002f1395be1257,"{u'building': u'284', u'street': u'Prospect Pa...",Brooklyn,American,"[{u'date': 2014-11-19 00:00:00, u'grade': u'A'...",NaN,The Movable Feast,40361606
20,562601afba002f1395be1258,"{u'building': u'129-08', u'street': u'20 Avenu...",Queens,Delicatessen,"[{u'date': 2014-08-16 00:00:00, u'grade': u'A'...",NaN,Sal'S Deli,40361618
21,562601afba002f1395be1259,"{u'building': u'7715', u'street': u'18 Avenue'...",Brooklyn,American,"[{u'date': 2014-04-16 00:00:00, u'grade': u'A'...",NaN,C & C Catering Service,40357437
22,562601afba002f1395be125a,"{u'building': u'759', u'street': u'Broadway', ...",Manhattan,Delicatessen,"[{u'date': 2014-01-21 00:00:00, u'grade': u'A'...",NaN,Bully'S Deli,40361708
23,562601afba002f1395be125b,"{u'building': u'3406', u'street': u'10 Street'...",Queens,Delicatessen,"[{u'date': 2014-03-19 00:00:00, u'grade': u'A'...",NaN,Steve Chu'S Deli & Grocery,40361998
24,562601afba002f1395be125c,"{u'building': u'502', u'street': u'Amsterdam A...",Manhattan,Chicken,"[{u'date': 2014-09-15 00:00:00, u'grade': u'A'...",NaN,Harriet'S Kitchen,40362098
25,562601afba002f1395be125d,"{u'building': u'730', u'street': u'Columbus Av...",Manhattan,American,"[{u'date': 2014-09-12 00:00:00, u'grade': u'B'...",NaN,P & S Deli Grocery,40362264
26,562601afba002f1395be125e,"{u'building': u'18', u'street': u'West Houston...",Manhattan,American,"[{u'date': 2014-04-03 00:00:00, u'grade': u'A'...",NaN,Angelika Film Center,40362274
27,562601afba002f1395be125f,"{u'building': u'531', u'street': u'Myrtle Aven...",Brooklyn,Hamburgers,"[{u'date': 2014-03-18 00:00:00, u'grade': u'A'...",NaN,White Castle,40362344
28,562601afba002f1395be1260,"{u'building': u'60', u'street': u'Wall Street'...",Manhattan,Turkish,"[{u'date': 2014-09-26 00:00:00, u'grade': u'A'...",NaN,The Country Cafe,40362715
29,562601afba002f1395be1261,"{u'building': u'103-05', u'street': u'37 Avenu...",Queens,Chinese,"[{u'date': 2014-04-21 00:00:00, u'grade': u'A'...",NaN,Ho Mei Restaurant,40362432
...,...,...,...,...,...,...,...,...
25330,562601b2ba002f1395be7540,"{u'building': u'7', u'street': u'Corson Ave', ...",Staten Island,Other,[],NaN,,50018948
25331,562601b2ba002f1395be7541,"{u'building': u'326', u'street': u'Dekalb Ave'...",Brooklyn,Other,[],NaN,Luigis Pizzeria,50018950
25332,562601b2ba002f1395be7542,"{u'building': u'190', u'street': u'Nassau Ave'...",Brooklyn,Other,[],NaN,Northside Bakery,50018952
25333,562601b2ba002f1395be7543,"{u'building': u'307', u'street': u'Nelson Ave'...",Staten Island,Other,[],NaN,Christine'S Restaurant,50018953
25334,562601b2ba002f1395be7544,"{u'building': u'6635', u'street': u'Grand Ave'...",Queens,Other,[],NaN,,50018956
25335,562601b2ba002f1395be7545,"{u'building': u'208', u'street': u'W 13Th St',...",Manhattan,Other,[],NaN,Think Coffee,50018968
25336,562601b2ba002f1395be7546,"{u'building': u'425', u'street': u'W 15Th St',...",Manhattan,Other,[],NaN,Doughnuttery,50018972
25337,562601b2ba002f1395be7547,"{u'building': u'148', u'street': u'E 48Th St',...",Manhattan,Other,[],NaN,Residence Inn Manhattan Midtown East,50018974
25338,562601b2ba002f1395be7549,"{u'building': u'1218', u'street': u'Union St',...",Brooklyn,Other,[],NaN,Superwings & Things,50018977
25339,562601b2ba002f1395be754a,"{u'building': u'2172', u'street': u'86Th St', ...",Brooklyn,Other,[],NaN,,50018979
25340,562601b2ba002f1395be754b,"{u'building': u'3519', u'street': u'Broadway',...",Queens,Other,[],NaN,Mokja,50018980
25341,562601b2ba002f1395be754c,"{u'building': u'4028', u'street': u'Main St', ...",Queens,Other,[],NaN,,50018982
25342,562601b2ba002f1395be754d,"{u'building': u'13542', u'street': u'Roosevelt...",Queens,Other,[],NaN,,50018984
25343,562601b2ba002f1395be754e,"{u'building': u'971', u'street': u'Amsterdam A...",Manhattan,Other,[],NaN,Subway,50018987
25344,562601b2ba002f1395be754f,"{u'building': u'325', u'street': u'W 33Rd St',...",Manhattan,Other,[],NaN,Fairfield Inn Suites Penn Station,50018989
25345,562601b2ba002f1395be7550,"{u'building': u'399', u'street': u'Mother Gast...",Brooklyn,Other,[],NaN,,50018993
25346,562601b2ba002f1395be7551,"{u'building': u'461', u'street': u'Port Richmo...",Staten Island,Other,[],NaN,Indian Oven,50018994
25347,562601b2ba002f1395be7552,"{u'building': u'921', u'street': u'Cortelyou R...",Brooklyn,Other,[],NaN,Cold Press'D,50018995
25348,562601b2ba002f1395be7553,"{u'building': u'987', u'street': u'1St Ave', u...",Manhattan,Vietnamese/Cambodian/Malaysia,"[{u'date': 2015-01-20 00:00:00, u'grade': u'No...",NaN,Pho Saigon,50018008
25349,562602a226a813276cd4fe7e,"{u'building': u'1480', u'street': u'2 Avenue',...",Manhattan,Italian,"[{u'date': 2014-10-01 00:00:00, u'grade': u'A'...",NaN,Vella,41704620
25350,562601b2ba002f1395be6aa3,"{u'building': u'30', u'street': u'East 30 St...",Manhattan,Category To Be Determined,[],2015-10-20 09:21:35.597000,Marta,50010857
25351,562601b2ba002f1395be732f,"{u'building': u'106', u'street': u'Lexington A...",Manhattan,Category To Be Determined,[],2015-10-20 09:21:35.618000,Kokum,50017817
25352,562601b2ba002f1395be7345,"{u'building': u'232', u'street': u'East 28 S...",Manhattan,Category To Be Determined,[],2015-10-20 09:21:35.618000,Chola,50017851
25353,562601b2ba002f1395be7348,"{u'building': u'102', u'street': u'Lexington A...",Manhattan,Category To Be Determined,[],2015-10-20 09:21:35.619000,Haldi,50017856
25354,562601b2ba002f1395be73d0,"{u'building': u'20', u'street': u'E 40Th St', ...",Manhattan,Category To Be Determined,[],2015-10-20 09:21:35.620000,Gregory'S Coffee,50018146
25355,562601b2ba002f1395be7409,"{u'building': u'462', u'street': u'1St Ave', u...",Manhattan,Category To Be Determined,[],2015-10-20 09:21:35.620000,,50018271
25356,562601b2ba002f1395be742d,"{u'building': u'204', u'street': u'E 38Th St',...",Manhattan,Category To Be Determined,[],2015-10-20 09:21:35.620000,Sons Of Thunder,50018350
25357,562601b2ba002f1395be747f,"{u'building': u'76', u'street': u'Madison Ave'...",Manhattan,Category To Be Determined,[],2015-10-20 09:21:35.621000,Exki Ny 002,50018507
25358,562601b2ba002f1395be74d7,"{u'building': u'14', u'street': u'E 34Th St', ...",Manhattan,Category To Be Determined,[],2015-10-20 09:21:35.621000,,50018695
25359,562601b2ba002f1395be7548,"{u'building': u'171', u'street': u'Madison Ave...",Manhattan,Category To Be Determined,[],2015-10-20 09:21:35.622000,,50018975